// Fixed list of SaltCity companies (locations). Single source of truth for
// both the /evangelism form dropdown and the /api/evangelism validation.
export const COMPANIES = [
  "AGBARHO",
  "AIRPORT ROAD/MOSHESHE",
  "AJAMIMOGHA",
  "ALEGBOR",
  "BENDEL ESTATE-1",
  "BENDEL ESTATE-2",
  "EBRUMEDE-OSUBI",
  "EDJEBA 1",
  "EDJEBA 2",
  "EFFURUN ROUNDABOUT",
  "EKPAN MAIN TOWN",
  "ENHEREN 1",
  "ENHERHEN 2",
  "GARAGE 1",
  "GIWAMU",
  "JAKPA 1",
  "JAKPA-2",
  "JAKPA 3",
  "JAKPA 4",
  "JAKPA 5",
  "KOSINI 1",
  "KOSINI 2",
  "LONDON OPI",
  "NIGERCAT",
  "NNPC-2",
  "OKERE-UGBORIKKO-POKOKO-1",
  "OKERE-UGBORIKKO-POKOKO-2",
  "OKERE-URHOBO-1",
  "OKERE-URHOBO-2",
  "OKERE-URHOBO-3",
  "OKOLOBA",
  "OKUMAGBA AVENUE - CINEMA 1",
  "OKUMAGBA AVENUE - CINEMA 2",
  "OKUMAGBA AVENUE - CINEMA 3",
  "OTOKUTU/OPETE",
  "PTI",
  "UBANGWE",
  "UDU",
  "UGBOMRO",
  "UGBOROKE",
  "UGHELLI",
] as const;
